DROP TABLE IF EXISTS TBL_STORE;

CREATE TABLE TBL_STORE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  city VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) DEFAULT NULL,
  zip varchar(25) NOT NULL
);